version: '3.9'

services:

#  dbpostgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_DB: restjava
#      POSTGRES_USER: adriano
#      POSTGRES_PASSWORD: adr1234
#    ports:
#      - 5434:5432
#    networks:
#      - rest_java

  dbmysql:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: restjava
      MYSQL_USER: adriano
      MYSQL_PASSWORD: adr123
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3310
    expose:
      - 3310
    volumes:
      - /opt/mysql-data:/var/lib/mysql8
    networks:
      - rest_java

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8090:8080
#    networks:
#      - rest_java

  rest-java:
    image: aaanm13/rest-java
    restart: always
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://host.docker.internal:3310/restjava?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 8100:8100
    command: mvn spring-boot:run
    depends_on: 
      - dbmysql
    networks:
      - rest_java
    
networks:
  rest_java:
    driver: bridge
  